### ISSUE TITLE
Testeo 2

### ISSUE THREAD

**Issue by FlaviaBravo** [PedroR01/Artimanias2024#4]
**Fecha:** 04.11.2024
**Dispositivo:** Notebook Lenovo | 1920x1080 |
**Tipo:** Estético 

**Error:** La carpeta en el escritorio que se llama 'Mapping' queda fuera de pantalla en la resolución de notebook 1920x1080, y también es tapada por el menú horizontal inferior

**Posible solución:** Quizás para aprovechar tanto espacio de escritorio vacío, seria mejor que se ordenen las carpetas en forma de grilla. Esta grilla considero que sería la mejor opción visual. Otra opción, pero no optimo,  quizás sería aprovechar que sobra espacio cerca del margen superior de la pantalla, y subir la posición 'eje y' de las carpetas. 

![escritorio](https://github.com/user-attachments/assets/1e232041-998b-41e7-a643-f5b935e5186e)

**Comment by PedroR01** [comment]
¡Hola Flavia, gracias por el reporte!

Actualmente, **la rama con los cambios actualizados se encuentra en la rama `test`**, una vez que todo lo funcional funcione sin problemas haremos el `merge` en la rama `main`, por lo tanto, por favor ten en cuenta que **la rama `main` no refleja la última versión en desarrollo**. 
Por otro lado, **también se encuentra para probar el `deploy` en Github Pages**, en el cual se pueden probar optimizaciones y velocidades de carga.

¡Saludos!
